package com.project.taskmanagement.enums;

public enum NotificationType {
    PROJECT_MEMBER_ADDED,
    PROJECT_MEMBER_REMOVED,
    PROJECT_MEMBER_ROLE_CHANGED,
    PROJECT_UPDATED,
    PROJECT_STATUS_CHANGED,
    PROJECT_DELETED,

    TASK_ASSIGNED,
    TASK_STATUS_CHANGED,
    TASK_READY_FOR_TEST,
    TASK_REOPENED,
    TASK_OVERDUE,
    TASK_UNASSIGNED,
    TASK_BLOCKED,
    TASK_CANCELLED,
    TASK_COMMENTED,
    TASK_MENTIONED,
    TASK_IMPORT_COMPLETED,
    TASK_IMPORT_FAILED,
    TASK_RISK_HIGH,
    TASK_RISK_CRITICAL,
    TASK_DUE_SOON,
    TASK_DEPENDENCY_RISK,
    
    SPRINT_TASKS_AT_RISK,
    SPRINT_ENDING_SOON,
    SPRINT_PROGRESS_AT_RISK,

    BUG_CREATED,
    BUG_ASSIGNED,
    BUG_STATUS_CHANGED,
    BUG_REOPENED,
    BUG_CRITICAL,
    BUG_COMMENTED,
    BUG_EVIDENCE_ADDED,
    BUG_ATTACHMENT_ADDED,

    COMMENT_MENTIONED,

    SPRINT_STARTED,
    SPRINT_ENDING,
    SPRINT_UPDATED,
    SPRINT_COMPLETED,
    SPRINT_CREATED,
    SPRINT_CANCELLED,

    BACKLOG_ITEM_CREATED,
    BACKLOG_ITEM_UPDATED,
    BACKLOG_ITEM_DELETED,
    BACKLOG_ITEM_STATUS_CHANGED,
    BACKLOG_ITEM_PRIORITY_CHANGED,
    BACKLOG_ITEM_POSITION_CHANGED,
    BACKLOG_ITEM_ADDED_TO_SPRINT,
    BACKLOG_ITEM_REMOVED_FROM_SPRINT,

}
