package com.project.taskmanagement.enums;

public enum NotificationType {
    PROJECT_MEMBER_ADDED,
    PROJECT_MEMBER_REMOVED,
    PROJECT_MEMBER_ROLE_CHANGED,
    PROJECT_UPDATED,
    PROJECT_STATUS_CHANGED,
    PROJECT_DELETED,

    TASK_ASSIGNED,
    TASK_STATUS_CHANGED,
    TASK_READY_FOR_TEST,
    TASK_REOPENED,
    TASK_OVERDUE,

    BUG_CREATED,
    BUG_ASSIGNED,

    COMMENT_MENTIONED,

    SPRINT_STARTED,
    SPRINT_ENDING,
    SPRINT_UPDATED,
    SPRINT_COMPLETED,
    SPRINT_CREATED,
    SPRINT_CANCELLED,

    BACKLOG_ITEM_CREATED,
    BACKLOG_ITEM_UPDATED,
    BACKLOG_ITEM_DELETED,
    BACKLOG_ITEM_STATUS_CHANGED,
    BACKLOG_ITEM_PRIORITY_CHANGED,
    BACKLOG_ITEM_POSITION_CHANGED,
    BACKLOG_ITEM_ADDED_TO_SPRINT,
    BACKLOG_ITEM_REMOVED_FROM_SPRINT,

}