package com.project.taskmanagement.enums;

public enum ProjectActivityAction {
    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_STATUS_CHANGED,
    PROJECT_DELETED,
    MEMBER_ADDED,
    MEMBER_REMOVED,
    MEMBER_ROLE_CHANGED,
    SPRINT_CREATED,
    SPRINT_STARTED,
    SPRINT_COMPLETED,
    BACKLOG_ITEM_CREATED,
    BACKLOG_PRIORITY_CHANGED,
    TASK_CREATED,
    TASK_UPDATED,
    TASK_ASSIGNED,
    TASK_STATUS_CHANGED,
    BUG_CREATED,
    COMMENT_CREATED
}