package com.project.taskmanagement.enums;

public enum ProjectActivityAction {

    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_STATUS_CHANGED,
    PROJECT_DELETED,

    MEMBER_ADDED,
    MEMBER_REMOVED,
    MEMBER_ROLE_CHANGED,

    SPRINT_CREATED,
    SPRINT_UPDATED,
    SPRINT_STARTED,
    SPRINT_COMPLETED,
    SPRINT_CANCELLED,

    BACKLOG_ITEM_CREATED,
    BACKLOG_ITEM_UPDATED,
    BACKLOG_ITEM_DELETED,
    BACKLOG_ITEM_STATUS_CHANGED,
    BACKLOG_ITEM_PRIORITY_CHANGED,
    BACKLOG_ITEM_ADDED_TO_SPRINT,
    BACKLOG_ITEM_REMOVED_FROM_SPRINT,
    BACKLOG_ITEM_POSITION_CHANGED,

    TASK_CREATED,
    TASK_UPDATED,
    TASK_ASSIGNED,
    TASK_STATUS_CHANGED,
    TASK_DELETED,
    TASK_UNASSIGNED,
    TASK_PRIORITY_CHANGED,
    TASK_POSITION_CHANGED,
    TASK_IMPORTED,
    TASK_MOVED_TO_SPRINT,
    TASK_REMOVED_FROM_SPRINT,
    TASK_BLOCKED,
    TASK_REOPENED,
    TASK_CANCELLED,
    TASK_UNBLOCKED,
    TASK_DEPENDENCY_ADDED,
    TASK_DEPENDENCY_REMOVED,
    TASK_RISK_SCANNED,
    TASK_RISK_LEVEL_CHANGED,


    BUG_CREATED,
    BUG_UPDATED,
    BUG_ASSIGNED,
    BUG_UNASSIGNED,
    BUG_STATUS_CHANGED,
    BUG_SEVERITY_CHANGED,
    BUG_PRIORITY_CHANGED,
    BUG_DELETED,
    BUG_COMMENT_CREATED,
    BUG_COMMENT_UPDATED,
    BUG_COMMENT_DELETED,
    BUG_EVIDENCE_CREATED,
    BUG_EVIDENCE_UPDATED,
    BUG_EVIDENCE_DELETED,
    BUG_ATTACHMENT_UPLOADED,
    BUG_ATTACHMENT_DELETED,

    ATTACHMENT_UPLOADED,
    ATTACHMENT_DELETED,

    COMMENT_CREATED,
    COMMENT_UPDATED,
    COMMENT_DELETED,

    TIME_LOG_CREATED,
    TIME_LOG_UPDATED,
    TIME_LOG_DELETED
}
